{% set name = "tephi" %}
{% set version = "0.2.1" %}
{% set sha256 = "10906b873c5f9fd8019053c1d5566caa1560a1fdca402ec5a3742ab4bc5731fa" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/SciTools/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps  -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - matplotlib-base
    - numpy >=1.14
    - scipy

test:
  imports:
    - tephi

about:
  home: http://tephi.readthedocs.org/
  license: LGPL-3.0
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Tephigram plotting in Python

extra:
  recipe-maintainers:
    - bjlittle
    - trexfeathers 
