{% set version = "0.2.3" %}

package:
  name: tephi
  version: {{ version }}

source:
  fn: tephi-{{ version }}.tar.gz
  url: https://github.com/SciTools/tephi/archive/v{{ version }}.tar.gz
  sha256: af0327ca38055e03b02efe9aa3c8abe080942828783eed7d088486b7c9b91967
  patches:
    - setup-fix.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps  -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - matplotlib-base
    - numpy >=1.14
    - scipy

test:
  imports:
    - tephi

about:
  home: http://tephi.readthedocs.org/
  license: LGPL-3
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Tephigram plotting in Python

extra:
  recipe-maintainers:
    - bjlittle
    - trexfeathers
